name: Odoo Tests

on:
  push:
    branches:
      - dev
      - test
  pull_request:
    branches:
      - dev
      - test

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Mensaje temporal para tests
        run: |
          echo "Aquí podrías preparar tests en el futuro"
