name: Odoo CI

on:
  pull_request:
    branches:
      - dev
      - test

jobs:
  odoo-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: odoo
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U odoo"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    container:
      image: odoo:18
      options: --user root

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar dependencias adicionales si es necesario
        run: |
          apt-get update && apt-get install -y git

      - name: Ejecutar pruebas de Odoo
        env:
          PGHOST: postgres
          PGPORT: 5432
          PGUSER: odoo
          PGPASSWORD: odoo
        run: |
          odoo --addons-path=custom_addons
              --db_user=odoo \
              --test-enable \
              --stop-after-init \
              --log-level=test
