name: Odoo CI

on:
  push:
    branches:
      - dev
      - test
      - main
  pull_request:
    branches:
      - dev
      - test
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pylint pylint-odoo

      - name: Lint with flake8
        run: |
          flake8 ./custom_addons --exclude=__pycache__

      - name: Lint with pylint-odoo
        run: |
          pylint --load-plugins=pylint_odoo ./custom_addons --disable=all --enable=odoo