name: Odoo CI

on:
  pull_request:
    branches:
      - dev
      - test
      - main

jobs:
  odoo-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: odoo
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U odoo"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    container:
      image: odoo:18
      options: --user root

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Instalar dependencias
        run: |
          apt-get update && apt-get install -y git python3-flake8

      - name: Validar estilo de c贸digo (flake8)
        run: |
          flake8 custom_addons --max-line-length=120 || true

      - name: Detectar m贸dulos en custom_addons
        id: detect_modules
        run: |
          MODS=$(ls custom_addons | grep -vE '^\.|__pycache__' | paste -sd "," -)
          echo "MODS=$MODS" >> $GITHUB_ENV

      - name: Ejecutar pruebas de Odoo con m贸dulos detectados
        env:
          PGHOST: postgres
          PGPORT: 5432
          PGUSER: odoo
          PGPASSWORD: odoo
        run: |
          echo "Instalando m贸dulos: $MODS"
          odoo --addons-path=/usr/lib/python3/dist-packages/odoo/addons,custom_addons \
            --db_user=odoo \
            --init=$MODS \
            --test-enable \
            --stop-after-init \
            --log-level=test
