name: Odoo CI

on:
  pull_request:
    branches:
      - dev
      - test

jobs:
  odoo-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: odoo
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: odoo
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U odoo" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias del sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-dev build-essential libxslt-dev libzip-dev libldap2-dev libsasl2-dev \
            libpq-dev libjpeg-dev libffi-dev libssl-dev libxml2-dev libpng-dev \
            node-less gcc npm

      - name: Instalar dependencias Python
        run: |
          python -m pip install --upgrade pip
          pip install wheel setuptools
          pip install -r requirements.txt || true  # en caso de que uses uno

      - name: Ejecutar tests de Odoo
        env:
          PGHOST: localhost
          PGPORT: 5432
          PGUSER: odoo
          PGPASSWORD: odoo
        run: |
          ./odoo-bin \
            --addons-path=addons,custom_addons \
            --db_user=odoo \
            --db_password=odoo \
            --test-enable \
            --stop-after-init \
            --log-level=test
            